#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("GooglePlusSignIn.Resource", IsApplication=true)]

namespace GooglePlusSignIn
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circleColor = global::GooglePlusSignIn.Resource.Attribute.circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circularProgressBarStyle = global::GooglePlusSignIn.Resource.Attribute.circularProgressBarStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_gravity = global::GooglePlusSignIn.Resource.Attribute.circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate = global::GooglePlusSignIn.Resource.Attribute.circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate_interval = global::GooglePlusSignIn.Resource.Attribute.circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_marker_progress = global::GooglePlusSignIn.Resource.Attribute.circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress = global::GooglePlusSignIn.Resource.Attribute.circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_background_color = global::GooglePlusSignIn.Resource.Attribute.circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_color = global::GooglePlusSignIn.Resource.Attribute.circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_stroke_width = global::GooglePlusSignIn.Resource.Attribute.circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate = global::GooglePlusSignIn.Resource.Attribute.indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate_interval = global::GooglePlusSignIn.Resource.Attribute.indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.innerSize = global::GooglePlusSignIn.Resource.Attribute.innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.max = global::GooglePlusSignIn.Resource.Attribute.max;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinned = global::GooglePlusSignIn.Resource.Attribute.pinned;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinnedDrawable = global::GooglePlusSignIn.Resource.Attribute.pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progress = global::GooglePlusSignIn.Resource.Attribute.progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressButtonStyle = global::GooglePlusSignIn.Resource.Attribute.progressButtonStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressColor = global::GooglePlusSignIn.Resource.Attribute.progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.shadowDrawable = global::GooglePlusSignIn.Resource.Attribute.shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.unpinnedDrawable = global::GooglePlusSignIn.Resource.Attribute.unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_circle_color = global::GooglePlusSignIn.Resource.Color.progress_default_circle_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_progress_color = global::GooglePlusSignIn.Resource.Color.progress_default_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_dark = global::GooglePlusSignIn.Resource.Color.refractored_background_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_dark = global::GooglePlusSignIn.Resource.Color.refractored_background_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_light = global::GooglePlusSignIn.Resource.Color.refractored_background_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_light = global::GooglePlusSignIn.Resource.Color.refractored_background_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark = global::GooglePlusSignIn.Resource.Color.refractored_bright_foreground_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark_disabled = global::GooglePlusSignIn.Resource.Color.refractored_bright_foreground_dark_disabled;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_dark = global::GooglePlusSignIn.Resource.Color.refractored_bright_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_light = global::GooglePlusSignIn.Resource.Color.refractored_bright_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_dark = global::GooglePlusSignIn.Resource.Color.refractored_bright_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_light = global::GooglePlusSignIn.Resource.Color.refractored_bright_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_light = global::GooglePlusSignIn.Resource.Color.refractored_bright_foreground_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_dark = global::GooglePlusSignIn.Resource.Color.refractored_dim_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_light = global::GooglePlusSignIn.Resource.Color.refractored_dim_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_dark = global::GooglePlusSignIn.Resource.Color.refractored_dim_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_light = global::GooglePlusSignIn.Resource.Color.refractored_dim_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_dark = global::GooglePlusSignIn.Resource.Color.refractored_highlighted_text_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_light = global::GooglePlusSignIn.Resource.Color.refractored_highlighted_text_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_dark = global::GooglePlusSignIn.Resource.Color.refractored_hint_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_light = global::GooglePlusSignIn.Resource.Color.refractored_hint_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_bright = global::GooglePlusSignIn.Resource.Color.refractored_holo_blue_bright;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_dark = global::GooglePlusSignIn.Resource.Color.refractored_holo_blue_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_light = global::GooglePlusSignIn.Resource.Color.refractored_holo_blue_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_dark = global::GooglePlusSignIn.Resource.Color.refractored_holo_green_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_light = global::GooglePlusSignIn.Resource.Color.refractored_holo_green_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_dark = global::GooglePlusSignIn.Resource.Color.refractored_holo_orange_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_light = global::GooglePlusSignIn.Resource.Color.refractored_holo_orange_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_purple = global::GooglePlusSignIn.Resource.Color.refractored_holo_purple;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_dark = global::GooglePlusSignIn.Resource.Color.refractored_holo_red_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_light = global::GooglePlusSignIn.Resource.Color.refractored_holo_red_light;
			global::com.refractored.monodroidtoolkit.Resource.Dimension.progress_inner_size = global::GooglePlusSignIn.Resource.Dimension.progress_inner_size;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_pinned = global::GooglePlusSignIn.Resource.Drawable.pin_progress_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_shadow = global::GooglePlusSignIn.Resource.Drawable.pin_progress_shadow;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_unpinned = global::GooglePlusSignIn.Resource.Drawable.pin_progress_unpinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_normal_holo = global::GooglePlusSignIn.Resource.Drawable.scrubber_control_normal_holo;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_pressed_holo = global::GooglePlusSignIn.Resource.Drawable.scrubber_control_pressed_holo;
			global::com.refractored.monodroidtoolkit.Resource.Id.bottom = global::GooglePlusSignIn.Resource.Id.bottom;
			global::com.refractored.monodroidtoolkit.Resource.Id.center = global::GooglePlusSignIn.Resource.Id.center;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_horizontal = global::GooglePlusSignIn.Resource.Id.center_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_vertical = global::GooglePlusSignIn.Resource.Id.center_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip = global::GooglePlusSignIn.Resource.Id.clip;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_horizontal = global::GooglePlusSignIn.Resource.Id.clip_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_vertical = global::GooglePlusSignIn.Resource.Id.clip_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.end = global::GooglePlusSignIn.Resource.Id.end;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill = global::GooglePlusSignIn.Resource.Id.fill;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_horizontal = global::GooglePlusSignIn.Resource.Id.fill_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_vertical = global::GooglePlusSignIn.Resource.Id.fill_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.left = global::GooglePlusSignIn.Resource.Id.left;
			global::com.refractored.monodroidtoolkit.Resource.Id.right = global::GooglePlusSignIn.Resource.Id.right;
			global::com.refractored.monodroidtoolkit.Resource.Id.start = global::GooglePlusSignIn.Resource.Id.start;
			global::com.refractored.monodroidtoolkit.Resource.Id.top = global::GooglePlusSignIn.Resource.Id.top;
			global::com.refractored.monodroidtoolkit.Resource.Integer.circular_indeterminent_interval = global::GooglePlusSignIn.Resource.Integer.circular_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Integer.progressbutton_indeterminent_interval = global::GooglePlusSignIn.Resource.Integer.progressbutton_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBar = global::GooglePlusSignIn.Resource.Style.CircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBarLight = global::GooglePlusSignIn.Resource.Style.CircularProgressBarLight;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton = global::GooglePlusSignIn.Resource.Style.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton_Pin = global::GooglePlusSignIn.Resource.Style.ProgressButton_Pin;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar = global::GooglePlusSignIn.Resource.Styleable.HoloCircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_gravity = global::GooglePlusSignIn.Resource.Styleable.HoloCircularProgressBar_circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate = global::GooglePlusSignIn.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval = global::GooglePlusSignIn.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress = global::GooglePlusSignIn.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress = global::GooglePlusSignIn.Resource.Styleable.HoloCircularProgressBar_circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color = global::GooglePlusSignIn.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_color = global::GooglePlusSignIn.Resource.Styleable.HoloCircularProgressBar_circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width = global::GooglePlusSignIn.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton = global::GooglePlusSignIn.Resource.Styleable.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_clickable = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_android_clickable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_focusable = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_android_focusable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_selectableItemBackground = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_android_selectableItemBackground;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_circleColor = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate_interval = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_innerSize = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_max = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_max;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinned = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinnedDrawable = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progress = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progressColor = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_shadowDrawable = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_unpinnedDrawable = global::GooglePlusSignIn.Resource.Styleable.ProgressButton_unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme = global::GooglePlusSignIn.Resource.Styleable.Theme;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme_circularProgressBarStyle = global::GooglePlusSignIn.Resource.Styleable.Theme_circularProgressBarStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010011
			public const int circleColor = 2130771985;
			
			// aapt resource value: 0x7f010022
			public const int circularProgressBarStyle = 2130772002;
			
			// aapt resource value: 0x7f01001a
			public const int circular_gravity = 2130771994;
			
			// aapt resource value: 0x7f010020
			public const int circular_indeterminate = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int circular_indeterminate_interval = 2130772001;
			
			// aapt resource value: 0x7f01001d
			public const int circular_marker_progress = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int circular_progress = 2130771996;
			
			// aapt resource value: 0x7f01001f
			public const int circular_progress_background_color = 2130771999;
			
			// aapt resource value: 0x7f01001e
			public const int circular_progress_color = 2130771998;
			
			// aapt resource value: 0x7f01001b
			public const int circular_stroke_width = 2130771995;
			
			// aapt resource value: 0x7f010018
			public const int indeterminate = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int indeterminate_interval = 2130771993;
			
			// aapt resource value: 0x7f010016
			public const int innerSize = 2130771990;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010010
			public const int max = 2130771984;
			
			// aapt resource value: 0x7f010017
			public const int pinned = 2130771991;
			
			// aapt resource value: 0x7f010013
			public const int pinnedDrawable = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int progress = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int progressButtonStyle = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int progressColor = 2130771986;
			
			// aapt resource value: 0x7f010015
			public const int shadowDrawable = 2130771989;
			
			// aapt resource value: 0x7f010006
			public const int uiCompass = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int uiRotateGestures = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int uiScrollGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiTiltGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiZoomControls = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomGestures = 2130771979;
			
			// aapt resource value: 0x7f010014
			public const int unpinnedDrawable = 2130771988;
			
			// aapt resource value: 0x7f01000c
			public const int useViewLifecycle = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int zOrderOnTop = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int common_action_bar_splitter = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int common_signin_btn_dark_text_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_signin_btn_dark_text_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_signin_btn_dark_text_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_signin_btn_dark_text_pressed = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int common_signin_btn_default_background = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int common_signin_btn_light_text_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_signin_btn_light_text_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_signin_btn_light_text_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_signin_btn_light_text_pressed = 2130968581;
			
			// aapt resource value: 0x7f040029
			public const int common_signin_btn_text_dark = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int common_signin_btn_text_light = 2130968618;
			
			// aapt resource value: 0x7f04000a
			public const int progress_default_circle_color = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int progress_default_progress_color = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int refractored_background_dark = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int refractored_background_holo_dark = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int refractored_background_holo_light = 2130968594;
			
			// aapt resource value: 0x7f04000d
			public const int refractored_background_light = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int refractored_bright_foreground_dark = 2130968590;
			
			// aapt resource value: 0x7f040010
			public const int refractored_bright_foreground_dark_disabled = 2130968592;
			
			// aapt resource value: 0x7f040015
			public const int refractored_bright_foreground_disabled_holo_dark = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int refractored_bright_foreground_disabled_holo_light = 2130968598;
			
			// aapt resource value: 0x7f040013
			public const int refractored_bright_foreground_holo_dark = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int refractored_bright_foreground_holo_light = 2130968596;
			
			// aapt resource value: 0x7f04000f
			public const int refractored_bright_foreground_light = 2130968591;
			
			// aapt resource value: 0x7f040018
			public const int refractored_dim_foreground_disabled_holo_dark = 2130968600;
			
			// aapt resource value: 0x7f04001b
			public const int refractored_dim_foreground_disabled_holo_light = 2130968603;
			
			// aapt resource value: 0x7f040017
			public const int refractored_dim_foreground_holo_dark = 2130968599;
			
			// aapt resource value: 0x7f04001a
			public const int refractored_dim_foreground_holo_light = 2130968602;
			
			// aapt resource value: 0x7f04001d
			public const int refractored_highlighted_text_holo_dark = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int refractored_highlighted_text_holo_light = 2130968606;
			
			// aapt resource value: 0x7f040019
			public const int refractored_hint_foreground_holo_dark = 2130968601;
			
			// aapt resource value: 0x7f04001c
			public const int refractored_hint_foreground_holo_light = 2130968604;
			
			// aapt resource value: 0x7f040028
			public const int refractored_holo_blue_bright = 2130968616;
			
			// aapt resource value: 0x7f040022
			public const int refractored_holo_blue_dark = 2130968610;
			
			// aapt resource value: 0x7f04001f
			public const int refractored_holo_blue_light = 2130968607;
			
			// aapt resource value: 0x7f040023
			public const int refractored_holo_green_dark = 2130968611;
			
			// aapt resource value: 0x7f040020
			public const int refractored_holo_green_light = 2130968608;
			
			// aapt resource value: 0x7f040027
			public const int refractored_holo_orange_dark = 2130968615;
			
			// aapt resource value: 0x7f040026
			public const int refractored_holo_orange_light = 2130968614;
			
			// aapt resource value: 0x7f040025
			public const int refractored_holo_purple = 2130968613;
			
			// aapt resource value: 0x7f040024
			public const int refractored_holo_red_dark = 2130968612;
			
			// aapt resource value: 0x7f040021
			public const int refractored_holo_red_light = 2130968609;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int progress_inner_size = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_signin_btn_icon_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_signin_btn_icon_disabled_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_focus_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_focus_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_focus_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_normal_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_normal_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_pressed_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_pressed_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_text_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_text_disabled_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_disabled_focus_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_focus_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_focus_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_focus_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_normal_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_normal_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_pressed_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_pressed_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int default_icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_launcher = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_plusone_medium_off_client = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_plusone_small_off_client = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_plusone_standard_off_client = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_plusone_tall_off_client = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Icon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int pin_progress_pinned = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int pin_progress_shadow = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int pin_progress_unpinned = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int scrubber_control_normal_holo = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int scrubber_control_pressed_holo = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int bottom = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int center = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int center_horizontal = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int center_vertical = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int clip = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int clip_horizontal = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int clip_vertical = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int end = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int fill = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int fill_horizontal = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int fill_vertical = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int hybrid = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int left = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int logout_button = 2131034133;
			
			// aapt resource value: 0x7f050000
			public const int none = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int normal = 2131034113;
			
			// aapt resource value: 0x7f050016
			public const int plus_one_button = 2131034134;
			
			// aapt resource value: 0x7f05001a
			public const int profile_about = 2131034138;
			
			// aapt resource value: 0x7f050017
			public const int profile_image = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int profile_name = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int profile_nickname = 2131034137;
			
			// aapt resource value: 0x7f050011
			public const int right = 2131034129;
			
			// aapt resource value: 0x7f050002
			public const int satellite = 2131034114;
			
			// aapt resource value: 0x7f050014
			public const int sign_in_button = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int start = 2131034130;
			
			// aapt resource value: 0x7f050003
			public const int terrain = 2131034115;
			
			// aapt resource value: 0x7f050013
			public const int top = 2131034131;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080001
			public const int circular_indeterminent_interval = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int progressbutton_indeterminent_interval = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06001a
			public const int app_name = 2131099674;
			
			// aapt resource value: 0x7f060014
			public const int auth_client_needs_enabling_title = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int auth_client_needs_installation_title = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int auth_client_needs_update_title = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int auth_client_play_services_err_notification_msg = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int auth_client_requested_by_msg = 2131099672;
			
			// aapt resource value: 0x7f060013
			public const int auth_client_using_bad_version_title = 2131099667;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_enable_button = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_enable_text = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_enable_title = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_button = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_install_text_phone = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_install_text_tablet = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_install_title = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_invalid_account_text = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_invalid_account_title = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_network_error_text = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_network_error_title = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_unknown_issue = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_unsupported_text = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_unsupported_title = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_update_button = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_text = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_update_title = 2131099655;
			
			// aapt resource value: 0x7f060011
			public const int common_signin_button_text = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int common_signin_button_text_long = 2131099666;
			
			// aapt resource value: 0x7f060019
			public const int hello = 2131099673;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090005
			public const int BaseDarkTheme = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int BaseTheme = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int CircularProgressBar = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int CircularProgressBarLight = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int ProgressButton = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int ProgressButton_Pin = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int Theme = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int ThemeDark = 2131296263;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] HoloCircularProgressBar = new int[]
			{
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001};
			
			// aapt resource value: 0
			public const int HoloCircularProgressBar_circular_gravity = 0;
			
			// aapt resource value: 6
			public const int HoloCircularProgressBar_circular_indeterminate = 6;
			
			// aapt resource value: 7
			public const int HoloCircularProgressBar_circular_indeterminate_interval = 7;
			
			// aapt resource value: 3
			public const int HoloCircularProgressBar_circular_marker_progress = 3;
			
			// aapt resource value: 2
			public const int HoloCircularProgressBar_circular_progress = 2;
			
			// aapt resource value: 5
			public const int HoloCircularProgressBar_circular_progress_background_color = 5;
			
			// aapt resource value: 4
			public const int HoloCircularProgressBar_circular_progress_color = 4;
			
			// aapt resource value: 1
			public const int HoloCircularProgressBar_circular_stroke_width = 1;
			
			public static int[] MapAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			public static int[] ProgressButton = new int[]
			{
					16842970,
					16842981,
					16843534,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 1
			public const int ProgressButton_android_clickable = 1;
			
			// aapt resource value: 0
			public const int ProgressButton_android_focusable = 0;
			
			// aapt resource value: 2
			public const int ProgressButton_android_selectableItemBackground = 2;
			
			// aapt resource value: 5
			public const int ProgressButton_circleColor = 5;
			
			// aapt resource value: 12
			public const int ProgressButton_indeterminate = 12;
			
			// aapt resource value: 13
			public const int ProgressButton_indeterminate_interval = 13;
			
			// aapt resource value: 10
			public const int ProgressButton_innerSize = 10;
			
			// aapt resource value: 4
			public const int ProgressButton_max = 4;
			
			// aapt resource value: 11
			public const int ProgressButton_pinned = 11;
			
			// aapt resource value: 7
			public const int ProgressButton_pinnedDrawable = 7;
			
			// aapt resource value: 3
			public const int ProgressButton_progress = 3;
			
			// aapt resource value: 6
			public const int ProgressButton_progressColor = 6;
			
			// aapt resource value: 9
			public const int ProgressButton_shadowDrawable = 9;
			
			// aapt resource value: 8
			public const int ProgressButton_unpinnedDrawable = 8;
			
			public static int[] Theme = new int[]
			{
					2130772002};
			
			// aapt resource value: 0
			public const int Theme_circularProgressBarStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
